server:
  port: 8761

spring:
  profiles: peer1
eureka:
  instance:
#    hostname: peer1
    prefer-ip-address: true
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://127.0.0.1:8769/
